spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: rjsgml33

  jpa:
    hibernate:
      ddl-auto: update # ???? ???? ??? ??
    properties:
      hibernate:
        show_sql: true # ???? ????? SQL? ??? ????
        format_sql: true # SQL? ? ??? ????
    database-platform: org.hibernate.dialect.MySQL8Dialect # ??? DBMS ???
